[package]
name = "baizekit-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
baizekit-serde = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

axum = "0.8.1"
tracing = "0.1.41"
utoipa = "5.3.1"