name: Publish workspace crates

on:
  push:
    tags:
      - '**-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces

      - name: Publish workspace crates
        run: cargo workspaces publish --from-git --yes
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}